
if(ENABLE_STATIC)
  set(LINK_TYPE "STATIC")
else()
  set(LINK_TYPE "SHARED")
endif() 

set(XERCESC ${PROJECT_ROOT}/src/xercesc)
file(REMOVE ${XERCESC}/util/Xerces_autoconf_config.hpp)

if(MSVC)
  file(COPY ${XERCESC}/util/Xerces_autoconf_config.msvc.hpp DESTINATION ${XERCESC})
  file(RENAME ${XERCESC}/Xerces_autoconf_config.msvc.hpp ${XERCESC}/util/Xerces_autoconf_config.hpp)
  set(XERCES_USE_TRANSCODER_WINDOWS 1)
  set(XERCES_USE_FILEMGR_WINDOWS 1)
  set(XERCES_USE_MUTEXMGR_WINDOWS 1)
  set(XERCES_USE_MSGLOADER_INMEMORY 1)
else(MSVC)
  set(XERCES_AUTOCONF "")

  if(NOT ENABLE_THREADS)
    set(APP_NO_THREADS 1)
  endif()
  include(check_headers)
  include(xerces_int_types)
  include(cxx_have_wchar)
  include(cxx_have_namespaces)
  include(cxx_have_std_namespace)
  include(cxx_have_std_libs)
  include(cxx_have_bool)
  include(cxx_have_delete)
  include(check_cpu)
  include(check_functions)
  include(xerces_transcoder_selection)
  include(xerces_netaccessor_selection)
  include(xerces_msgloader_selection)
  include(xerces_mutexmgr_selection)

 
  set(XERCES_PLATFORM_EXPORT "")
  set(XERCES_PLATFORM_IMPORT "")
  if(WIN32 OR MINGW OR MSYS)
    set(XERCES_PLATFORM_EXPORT "__declspec(dllexport)")
    set(XERCES_PLATFORM_IMPORT "__declspec(dllimport)")
  endif()

  if(WIN32 OR MINGW OR MSYS)
    set(XERCES_USE_FILEMGR_WINDOWS 1)
    set(XERCES_USE_FILEMGR_POSIX 0)

    #Define to use backslash as an extra path delimiter character
    set(XERCES_PATH_DELIMITER_BACKSLASH 1)
  else()
    set(XERCES_USE_FILEMGR_POSIX 1)
    set(XERCES_USE_FILEMGR_WINDOWS 0)
  endif() 
  
  # write config
  CONFIGURE_FILE(${PROJECT_ROOT}/src/xercesc/util/Xerces_autoconf_config.hpp.cmake.in ${PROJECT_ROOT}/src/xercesc/util/Xerces_autoconf_config.hpp)
  CONFIGURE_FILE(${PROJECT_ROOT}/config.h.cmake.in ${PROJECT_ROOT}/config.h)
  set(FLAGS_CXX_DEFAULT "${FLAGS_CXX_DEFAULT} -DHAVE_CONFIG_H")
  include_directories(${PROJECT_ROOT})
endif(MSVC)